maplecroft/urls.py
from django.conf.urls import url, include
from . import views
#from django.contrib import admin

urlpatterns = [
	#url( r'^admin/', admin.site.urls ),

	url( r'^$', views.index ),
	url( r'^twitterfeed/', include( 'twitterfeed.urls', namespace='twitterfeed' ) ),
]

twitterfeed/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url( r'^$', views.feedmap, name='feedmap' ),
]

twitterfeed/models.py
from django.db import models

class Country(models.Model):
	name = models.CharField( max_length=128, db_index=True )
	code = models.CharField( max_length=2 )
	longitude = models.DecimalField( max_digits=8, decimal_places=5 )
	latitude = models.DecimalField( max_digits=8, decimal_places=5 )

	def __str__( self ):
		return self.name

maplecroft/views.py
from django.shortcuts import render

def index( request ):
	return render( request, 'maplecroft/index.html' )

twitterfeed/views.py
from django.shortcuts import render
from django.conf import settings
from .models import Country
import twitter
import re

RX = re.compile( "#([a-zA-Z0-9]+)" )

def feedmap( request ):

	api = twitter.Api(
			consumer_key = settings.TWITTER_CONSUMER_KEY,
			consumer_secret = settings.TWITTER_CONSUMER_SECRET,
			access_token_key = settings.TWITTER_ACCESS_TOKEN,
			access_token_secret = settings.TWITTER_ACCESS_TOKEN_SECRET )

	tweets = api.GetUserTimeline( screen_name="MaplecroftRisk", count=10 )

	for i, tweet in enumerate( tweets ):
		tweet.id = i + 1

	tweets_by_country = {}

	for tweet in tweets:
		for tag in RX.findall( tweet.text ):
			countries = Country.objects.filter( name=tag )
			if countries.count() > 0:
				country = countries.first()

				tweets_by_country.setdefault( country, [] ).append( tweet.id )

	midpoint = (
		sum( map( lambda country: country.latitude, tweets_by_country.keys() ) ) / len(tweets_by_country),
		sum( map( lambda country: country.longitude, tweets_by_country.keys() ) ) / len(tweets_by_country) )

	return render( request, 'twitterfeed/feedmap.html', {
			'tweets': tweets,
			'tweets_by_country': tweets_by_country,
			'midpoint': midpoint,
			'GOOGLE_MAPS_API_KEY': settings.GOOGLE_MAPS_API_KEY
		} )

maplecroft/templates/maplecroft/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<title>{% block title %}{% endblock %}</title>

		<!-- Bootstrap -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->

		{% block head %}
		{% endblock %}
	</head>

	<body>
		{% block content %}
		{% endblock %}

		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>	

		{% block scripts %}
		{% endblock %}
	</body>
</html>

maplecroft/templates/maplecroft/index.html
{% extends 'maplecroft/base.html' %}

{% block title %}
	Verisk Maplecroft
{% endblock %}

{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-md-offset-4 col-md-4">
				<h1>Verisk Maplecroft</h1>

				<div class="list-group">
					<a href="{% url 'twitterfeed:feedmap' %}" class="list-group-item list-group-item-action">Twitter Feed Map</a>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

twitterfeed/templates/twitterfeed/feedmap.html
{% extends 'maplecroft/base.html' %}

{% block head %}
<style>
#map {
	height: 400px;
	width: 600px;
}
</style>
{% endblock %}

{% block title %}
	Verisk Maplecroft - Twitter Feed
{% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-md-offset-1 col-md-10">
			<h1>Latest 10 tweets</h1>

			<table class="table table-striped">
				<thead>
					<tr>
						<th></th>
						<th>Created at</th>
						<th>Message</th>
					</tr>
				</thead>
				<tbody>
					{% for tweet in tweets %}
						<tr>
							<td>{{forloop.counter}}</td>
							<td>{{tweet.created_at}}</td>
							<td>{{tweet.text}}</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
	<div class="row">
		<div class="col-md-offset-1 col-md-10">
			<div id="map"></div>
		</div>
	</div>
</div>
{% endblock %}}

{% block scripts %}
<script>
function initMap() {
	var mid = new google.maps.LatLng( {{midpoint.0}}, {{midpoint.1}} );

	var map = new google.maps.Map( document.getElementById( 'map' ), {
		zoom: 1,
		center: mid
	} );

	{% for country, tweet_ids in tweets_by_country.items %}
		var marker = new google.maps.Marker( {
			position: new google.maps.LatLng( {{country.latitude}}, {{country.longitude}} ),
			map: map,
			title: '{{country.name}} tweets {{tweet_ids}}'
		} );
	{% endfor %}
}
</script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key={{GOOGLE_MAPS_API_KEY}}&callback=initMap"></script>
{% endblock %}}